name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Nix
        uses: cachix/install-nix-action@v13
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes
            extra-substituters = https://ocaml.nix-cache.com
            extra-trusted-public-keys = ocaml.nix-cache.com-1:/xI2h2+56rwFfKyyFVbkJSeGqSIYMC/Je+7XXqGKDIY=
            extra-substituters = https://tezos.nix-cache.workers.dev
            extra-trusted-public-keys = tezos-nix-cache.marigold.dev-1:4nS7FPPQPKJIaNQcbwzN6m7kylv16UCWWgjeZZr2wXA= 
 
      - name: Build and run Ligo test
        run: |
          nix develop --command "ligo run test ./test.mligo"
 